scale_names_dict = {273: "Augmented Triad",
                    291: "Raga Lavangi",
                    1169: "Raga Mahathi",
                    549: "Raga Bhavani",
                    1161: "Bi Yu",
                    325: "Messiaen truncated mode 6",
                    1105: "Messiaen truncated mode 6 inverse",
                    293: "Raga Haripriya",
                    585: "Diminished Seventh",
                    2339: "Raga Kshanika",
                    2211: "Raga Gauri",
                    433: "Raga Zilaf",
                    425: "Raga Kokil Pancham",
                    2705: "Raga Mamata",
                    421: "Han-kumoi",
                    653: "Dorian Pentatonic",
                    1129: "Raga Jayakauns",
                    1187: "Kokin-joshi",
                    2641: "Raga Hindol",
                    1171: "Raga Manaranjani I",
                    557: "Raga Abhogi",
                    1163: "Raga Rukmangi",
                    1681: "Raga Valaji",
                    2629: "Raga Shubravarni",
                    397: "Hirajoshi",
                    419: "Hon-kumoi-joshi",
                    1123: "Iwato",
                    2257: "Lydian Pentatonic",
                    2609: "Raga Bhinna Shadja",
                    2601: "Raga Chandrakauns",
                    301: "Raga Audav Tukhari",
                    721: "Raga Dhavalashri",
                    2597: "Raga Rasranjani",
                    307: "Raga Megharanjani",
                    405: "Raga Bhupeshwari",
                    675: "Altered Pentatonic",
                    659: "Raga Rasika Ranjani",
                    1113: "Locrian Pentatonic 2",
                    403: "Raga Reva",
                    2249: "Raga Multani",
                    2353: "Raga Girija",
                    665: "Raga Mohanangi",
                    1225: "Raga Samudhra Priya",
                    2345: "Raga Chandrakauns",
                    2341: "Raga Priyadharshini",
                    395: "Balinese",
                    1585: "Raga Khamaji Durga",
                    2225: "Ionian Pentatonic",
                    2245: "Raga Vaijayanti",
                    2217: "Raga Nata",
                    331: "Raga Chhaya Todi",
                    709: "Raga Shri Kalyan",
                    1201: "Mixolydian Pentatonic",
                    1577: "Raga Chandrakauns (Kafi),",
                    2213: "Raga Desh",
                    299: "Raga Chitthakarshini",
                    689: "Raga Nagasvaravali",
                    1417: "Raga Shailaja",
                    1573: "Raga Guhamanohari",
                    2197: "Raga Hamsadhvani",
                    597: "Kung",
                    681: "Kyemyonjo",
                    1173: "Dominant Pentatonic",
                    1317: "Chaio",
                    1353: "Raga Harikauns",
                    661: "Major Pentatonic",
                    677: "Scottish Pentatonic",
                    1189: "Suspended Pentatonic",
                    1193: "Minor Pentatonic",
                    1321: "Blues Minor",
                    2247: "Raga Vijayasri",
                    945: "Raga Saravati",
                    2723: "Raga Jivantika",
                    467: "Raga Dhavalangam",
                    1257: "Blues scale",
                    2643: "Raga Hamsanandi",
                    931: "Raga Kalakanthi",
                    2611: "Raga Vasanta",
                    1489: "Raga Jyoti",
                    461: "Raga Syamalam",
                    2467: "Raga Padi",
                    3281: "Raga Vijayavasanta",
                    807: "Raga Suddha Mukhari",
                    2451: "Raga Bauli",
                    3273: "Raga Jivantini",
                    3269: "Raga Malarani",
                    711: "Raga Chandrajyoti",
                    3249: "Raga Tilang",
                    1209: "Raga Bhanumanjari",
                    2379: "Raga Gurjari Todi",
                    3237: "Raga Brindabani Sarang",
                    915: "Raga Kalagada",
                    2355: "Raga Lalita",
                    2347: "Raga Viyogavarali",
                    455: "Messiaen mode 5",
                    2275: "Messiaen Mode 5",
                    3185: "Messiaen mode 5 inverse",
                    2259: "Raga Mandari",
                    2227: "Raga Gaula",
                    1477: "Raga Jaganmohanam",
                    1699: "Raga Rasavali",
                    2701: "Hawaiian",
                    621: "Pyramid Hexatonic",
                    1683: "Raga Malayamarutam",
                    2637: "Raga Ranjani",
                    1115: "Superlocrian Hexamirror",
                    1675: "Raga Salagavarali",
                    1745: "Raga Vutari",
                    435: "Raga Purna Pancama",
                    2265: "Raga Rasamanjari",
                    1619: "Prometheus Neapolitan",
                    2381: "Takemitsu Tree Line mode 1",
                    1737: "Raga Madhukauns",
                    2349: "Raga Ghantana",
                    1587: "Raga Rudra Pancama",
                    2253: "Raga Amarasenapriya",
                    2481: "Raga Paraju",
                    1457: "Raga Kamalamanohari",
                    1733: "Raga Sarasvati",
                    2221: "Raga Sindhura Kafi",
                    1131: "Honchoshi plagal form",
                    1443: "Raga Phenadyuti",
                    1677: "Raga Manavi",
                    2613: "Raga Hamsa Vinodini",
                    619: "Double-Phrygian Hexatonic",
                    2357: "Raga Sarasanana",
                    1419: "Raga Kashyapi",
                    1581: "Raga Bagesri",
                    1713: "Raga Khamas",
                    2229: "Raga Nalinakanti",
                    2757: "Raga Nishadi",
                    427: "Raga Suddha Simantini",
                    1421: "Raga Trimurti",
                    1589: "Raga Rageshri",
                    2261: "Raga Caturangini",
                    2737: "Raga Hari Nata",
                    1357: "Takemitsu Tree Line mode 2",
                    725: "Raga Yamuna Kalyani",
                    1205: "Raga Siva Kambhoji",
                    1355: "Raga Bhavani",
                    1705: "Raga Manohari",
                    2725: "Raga Nagagandhari",
                    851: "Raga Hejjajji",
                    1229: "Raga Simharava",
                    1331: "Raga Vasantabhairavi",
                    2473: "Raga Takka",
                    693: "Arezzo Major Diatonic Hexachord",
                    1197: "Minor Hexatonic",
                    1323: "Ritsu",
                    1449: "Raga Gopikavasantam",
                    1701: "Dominant Seventh",
                    2709: "Raga Kumud",
                    845: "Raga Neelangi",
                    1235: "Messiaen truncated mode 2",
                    717: "Raga Vijayanagari",
                    2469: "Raga Bhinna Pancama",
                    685: "Raga Suddha Bangala",
                    1195: "Raga Gandharavam",
                    1445: "Raga Navamanohari",
                    2645: "Raga Mruganandana",
                    819: "Augmented Inverse",
                    2457: "Major Augmented",
                    691: "Raga Kalavati",
                    2453: "Raga Latika",
                    715: "Messiaen truncated mode 2",
                    1621: "Prometheus (Scriabin),",
                    2389: "Eskimo Hexatonic 2",
                    1365: "Whole-tone",
                    637: "Debussy's Heptatonic",
                    3271: "Mela Raghupriya",
                    3239: "Mela Tanarupi",
                    985: "Mela Sucaritra",
                    2759: "Mela Pavani",
                    3761: "Raga Madhuri",
                    981: "Mela Kantamani",
                    2727: "Mela Manavati",
                    3411: "Enigmatic",
                    3749: "Raga Sorati",
                    979: "Mela Dhavalambari",
                    3379: "Verdi's Scala enigmatica descending",
                    2503: "Mela Jhalavarali",
                    973: "Mela Syamalangi",
                    2471: "Mela Ganamurti",
                    3283: "Mela Visvambhari",
                    3275: "Mela Divyamani",
                    971: "Mela Gavambodhi",
                    3251: "Mela Hatakambari",
                    3243: "Mela Rupavati",
                    967: "Mela Salaga",
                    3637: "Raga Rageshri",
                    953: "Mela Yagapriya",
                    1735: "Mela Navanitam",
                    949: "Mela Mararanjani",
                    1261: "Modified Blues",
                    1703: "Mela Vanaspati",
                    947: "Mela Gayakapriya",
                    2521: "Mela Dhatuvardhani",
                    1497: "Mela Jyotisvarupini",
                    1479: "Mela Jalarnava",
                    941: "Mela Jhankaradhvani",
                    1447: "Mela Ratnangi",
                    2771: "Marva That",
                    2763: "Mela Suvarnangi",
                    939: "Mela Senavati",
                    1437: "Sabach ascending",
                    1653: "Minor Romani inverse",
                    2517: "Harmonic Lydian",
                    2739: "Mela Suryakanta",
                    1367: "Leading Whole-Tone inverse",
                    1397: "Major Locrian",
                    1493: "Lydian Minor",
                    2731: "Neapolitan Major",
                    3413: "Leading Whole-tone",
                    925: "Chromatic Hypodorian",
                    935: "Chromatic Dorian",
                    1255: "Chromatic Mixolydian",
                    2515: "Chromatic Hypolydian",
                    2675: "Chromatic Lydian",
                    3305: "Chromatic Hypophrygian",
                    3385: "Chromatic Phrygian",
                    1491: "Mela Namanarayani",
                    1769: "Blues Heptatonic II",
                    743: "Chromatic Hypophrygian inverse",
                    919: "Chromatic Phrygian Inverse",
                    1849: "Chromatic Hypodorian inverse",
                    2419: "Raga Lalita",
                    2507: "Todi That",
                    3257: "Mela Calanata",
                    3301: "Chromatic Mixolydian inverse",
                    871: "Locrian Double-flat 3 Double-flat 7",
                    923: "Ultraphrygian",
                    1651: "Asian",
                    2483: "Double Harmonic",
                    2509: "Double Harmonic Minor",
                    2873: "Ionian Augmented Sharp 2",
                    3289: "Lydian Sharp 2 Sharp 6",
                    1395: "Asian (a),",
                    1485: "Minor Romani",
                    2475: "Neapolitan Minor",
                    2745: "Mela Sulini",
                    3285: "Mela Citrambari",
                    2489: "Mela Gangeyabhusani",
                    3277: "Mela Nitimati",
                    1483: "Mela Bhavapriya",
                    1721: "Mela Vagadhisvari",
                    3253: "Mela Naganandini",
                    1465: "Mela Ragavardhani",
                    3245: "Mela Varunapriya",
                    877: "Moravian Pistalkova",
                    1747: "Mela Ramapriya",
                    2669: "Jeths' mode",
                    1739: "Mela Sadvidhamargini",
                    1753: "Hungarian Major",
                    2413: "Locrian nr.2",
                    2917: "Nohkan Flute scale",
                    875: "Locrian Double-flat 7",
                    1435: "Makam Huzzam",
                    1645: "Dorian flat 5",
                    1715: "Harmonic Minor inverse",
                    2485: "Harmonic Major",
                    2765: "Lydian Diminished",
                    2905: "Aeolian flat 1",
                    1371: "Superlocrian",
                    1389: "Minor Locrian",
                    1461: "Major-Minor",
                    1707: "Mela Natakapriya",
                    1749: "Acoustic",
                    2733: "Melodic Minor ascending",
                    2901: "Lydian Augmented",
                    859: "Ultralocrian",
                    1459: "Phrygian Dominant",
                    1643: "Locrian natural 6",
                    1741: "Altered Dorian",
                    2477: "Harmonic Minor",
                    2777: "Aeolian Harmonic",
                    2869: "Ionian Augmented",
                    1387: "Locrian",
                    1451: "Phrygian",
                    1453: "Aeolian",
                    1709: "Dorian",
                    1717: "Mixolydian",
                    2741: "Major",
                    2773: "Lydian",
                    2547: "Raga Ramkali",
                    1997: "Raga Cintamani",
                    3531: "Neveseri",
                    1659: "Maqam Shadd'araban",
                    2541: "Algerian",
                    3507: "Maqam Hijaz",
                    1403: "Espla's scale",
                    1711: "Adonai Malakh",
                    3499: "Hamel",
                    2539: "Half-diminished Bebop",
                    3443: "Verdi's Scala enigmatica",
                    1455: "Phrygian/Aeolian mixed",
                    1515: "Phrygian/Locrian mixed",
                    1725: "Minor Bebop",
                    1965: "Raga Mukhari",
                    2805: "Ishikotsucho",
                    3435: "Prokofiev",
                    3765: "Dominant Bebop",
                    3419: "Magan Abot",
                    3757: "Raga Mian Ki Malhar",
                    975: "Messiaen mode 4",
                    2535: "Messiaen mode 4",
                    3315: "Tcherepnin Octatonic mode 1",
                    3705: "Messiaen mode 4 inverse",
                    2803: "Raga Bhatiyar",
                    2995: "Raga Saurashtra",
                    3485: "Sabach",
                    2987: "Neapolitan Major and Minor mixed",
                    1499: "Bebop Locrian",
                    1723: "JG Octatonic",
                    1467: "Spanish Phrygian",
                    1773: "Blues scale II",
                    2907: "Magen Abot",
                    2997: "Major Bebop",
                    3501: "Maqam Nahawand",
                    1495: "Messiaen mode 6",
                    2795: "Van der Horst Octatonic",
                    3445: "Messiaen mode 6 inverse",
                    2779: "Shostakovich",
                    2989: "Bebop Minor",
                    1755: "Octatonic",
                    2925: "Diminished",
                    2029: "Kiourdi",
                    4021: "Raga Pahadi",
                    1789: "Blues Enneatonic II",
                    3767: "Chromatic Bebop",
                    4013: "Raga Pilu",
                    1519: "Locrian/Aeolian mixed",
                    1967: "Diatonic Dorian mixed",
                    1981: "Houseini",
                    3773: "Raga Malgunji",
                    3829: "Taishikicho",
                    1783: "Youlan scale",
                    2999: "Chromatic and Permuted Diatonic Dorian mixed",
                    3037: "nine tone scale",
                    3515: "Moorish Phrygian",
                    1911: "Messiaen mode 3",
                    3003: "Genus Chromaticum",
                    3549: "Messiaen mode 3 inverse",
                    2043: "Maqam Tarzanuyn",
                    3069: "Maqam Shawq Afza",
                    3519: "Raga Sindhi-Bhairavi",
                    3837: "Minor Pentatonic with leading tones",
                    4029: "Major/Minor mixed",
                    2015: "Messiaen mode 7",
                    3055: "Messiaen mode 7",
                    3575: "Symmetrical Decatonic",
                    3965: "Messiaen mode 7 inverse",
                    4095: "Chromatic",
                    1233: "Chinese"}
